index:
    path: /
    controller: App\Controller\PingPongController::indexAction

api:
    methods: post
    path: /api/ping
    controller: App\Controller\PingPongController::pingAction

any:
    methods: post
    path: /{req}
    controller: App\Controller\PingPongController::notFoundAction
    requirements:
        req: ".+"
